// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCECix7rjfnhlEGk6H0luDZuppuxSp9tdk',
    appId: '1:783934236738:web:031717a3e20430fbe7a5db',
    messagingSenderId: '783934236738',
    projectId: 'veganapp-77cf7',
    authDomain: 'veganapp-77cf7.firebaseapp.com',
    databaseURL: 'https://veganapp-77cf7-default-rtdb.firebaseio.com',
    storageBucket: 'veganapp-77cf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbgpzJcTR0tgIFIJjAK5NB4FsrZitZbI',
    appId: '1:783934236738:android:50050b1c9b955da0e7a5db',
    messagingSenderId: '783934236738',
    projectId: 'veganapp-77cf7',
    databaseURL: 'https://veganapp-77cf7-default-rtdb.firebaseio.com',
    storageBucket: 'veganapp-77cf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw824AB9LOxxGTjBI3kkhn3lZfxAB9mPY',
    appId: '1:783934236738:ios:3c4bb477403518c9e7a5db',
    messagingSenderId: '783934236738',
    projectId: 'veganapp-77cf7',
    databaseURL: 'https://veganapp-77cf7-default-rtdb.firebaseio.com',
    storageBucket: 'veganapp-77cf7.appspot.com',
    iosClientId: '783934236738-8rj0nnp4mbmripo155jaiq95agrt13c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.veganApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw824AB9LOxxGTjBI3kkhn3lZfxAB9mPY',
    appId: '1:783934236738:ios:3c4bb477403518c9e7a5db',
    messagingSenderId: '783934236738',
    projectId: 'veganapp-77cf7',
    databaseURL: 'https://veganapp-77cf7-default-rtdb.firebaseio.com',
    storageBucket: 'veganapp-77cf7.appspot.com',
    iosClientId: '783934236738-8rj0nnp4mbmripo155jaiq95agrt13c1.apps.googleusercontent.com',
    iosBundleId: 'com.example.veganApp',
  );
}
